# Generated by Django 2.1.1 on 2018-10-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_auto_20180922_1840'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('section_name', 'semester', 'course')},
        ),
    ]
